### ISSUE TITLE
other libraries are not optional to install and setup

### ISSUE THREAD

**Issue by maheshsgr** [blendtale/rn-formly#12]
Unable to resolve module `react-native-form-prorgress` even though i am not using it.

react-native-image-crop-picker is also mandatory

**Comment by irohitb** [comment]
@maheshsgr looking into it. Will update you in next 2 hours :)

**Comment by irohitb** [comment]
FIxed it. Trying it out, Will update you in few more minutes :)

**Comment by irohitb** [comment]
@maheshsgr  Fixed it. Trying it out and will update you in couple of minutes

**Comment by irohitb** [comment]
@maheshsgr  `react-native-image-crop-picker` is mandatory for now. I will have to restructure the code to make individual component importable/pluggable.  I have updated the docs for the time being to make `react-native-image-crop-picker` mandatory. 

Also, I have fixed the form-progress issue. You can do fresh npm install and let me know if it still doesn't work.
